### ISSUE TITLE
When connecting, I get "Failure" 

### ISSUE THREAD

**Issue by huzailhassan** [ErenKrt/ssh-push#1]
Run ErenKrt/ssh-push@1.0
✔️ Private key added on machine
✔️ Created zip as "build.zip"
/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:[32](https://github.com/Omnihorse-CHINATEAM/omnihorse-console-api-boot/actions/runs/4389484809/jobs/7687077705#step:28:33)375
      const err = new Error(errorMsg
                  ^

Error: Failure
    at 101 (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:32375:19)
    at SFTP.push (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:29949:11)
    at CHANNEL_DATA (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:25946:23)
    at 94 (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:36444:16)
    at Protocol.onPayload (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:29611:10)
    at AESGCMDecipherNative.decrypt (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:[34](https://github.com/Omnihorse-CHINATEAM/omnihorse-console-api-boot/actions/runs/4389484809/jobs/7687077705#step:28:35)891:26)
    at Protocol.parsePacket [as _parse] (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:29580:25)
    at Protocol.parse (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:27879:16)
    at Socket.<anonymous> (/home/runner/work/_actions/ErenKrt/ssh-push/1.0/dist/index.js:26134:21)
    at Socket.emit (node:events:527:28) {
  code: 4
}

**Comment by ErenKrt** [comment]
Hello, can u send your action yaml without secret envs ?

**Comment by huzailhassan** [comment]
Hello, sorry about that. This was because the EC2 was out of space

**Comment by ErenKrt** [comment]
i'm happy to hear that.
